[default]
mongo_uri= "mongodb://localhost:27017/todo"
mongo_dbname= "tasks"
title = "TODO"
extensions= [
    "app.database:configure",
    "app.commands:configure",
    "flask_bootstrap:Bootstrap",
    "app.views:configure",
    "app.plugins:configure",
]