[default]
secret_key= "5adc2c4ee71d826c2237e3d25619ed24b3719c764fea276d93391e50599e9523"
mongo_uri= "mongodb://localhost:27017/todo"
mongo_dbname= "tasks"
title = "TODO"
extensions= [
    "app.database:configure",
    "app.commands:configure",
    "flask_bootstrap:Bootstrap",
    "app.views:configure",
    "app.plugins:configure",
    "app.auth:configure"
]